export const events = [
  {
    id: 1,
    title: "CSE Programming Contest",
    category: "Competition",
    date: "2026-10-08",
    time: "10:00 AM",
    venue: "DIU Auditorium",
    description: "A programming contest for university students.",
    link: "https://facebook.com/",
    completed: false,
  },
  {
    id: 2,
    title: "AI & Machine Learning Seminar",
    category: "Seminar",
    date: "2026-10-10",
    time: "2:00 PM",
    venue: "Innovation Lab",
    description: "An introductory seminar about AI and machine learning.",
    link: "https://facebook.com/",
    completed: false,
  },
  {
    id: 3,
    title: "Cultural Night",
    category: "Cultural",
    date: "2026-10-15",
    time: "6:30 PM",
    venue: "DIU Main Auditorium",
    description: "An evening of music, performances and cultural activities.",
    link: "https://facebook.com/",
    completed: false,
  },
];